language: android

android:
  components:
    - platform-tools
    - build-tools-27.0.3
    - android-27
    - extra

after_script:
    - cat ./demo/build/outputs/lint-results.xml
    - cat ./library/build/outputs/lint-results.xml
    - cat ./utils-picasso/build/outputs/lint-results.xml

sudo: false